version: '3.7'

services:
    db:
      image: kartoza/postgis:latest
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        - my-network
      environment:
        - POSTGRES_DB=geodjango
        - POSTGRES_USER=root
        - POSTGRES_PASS=qwerty

    backend:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./docker/backend/Dockerfile
      volumes:
          - static_volume:/app/backend/staticfiles
          - media_volume:/app/backend/media
      entrypoint: /app/docker/backend/wsgi-entrypoint.sh
      networks:
        - my-network
      depends_on:
        - db
      ports:
        - 5000:5000

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  my-network:
