# Generated by Django 4.1.1 on 2022-09-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'verbose_name_plural': 'World borders'},
        ),
    ]
